shop/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from contact_us.views import contact_us

urlpatterns = [
    path('', include('books.urls')),
    path('about/', TemplateView.as_view(template_name='about_faq/about.html'), name='about'),
    path('faq/', TemplateView.as_view(template_name='about_faq/faq.html'), name='faq'),
    path('contact_us_form/', contact_us, name='contact_us_form'),
    path('order/', include('order.urls')),
    path('profile/', include('user_authentication.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls'))
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
                   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/user_authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import user_login, user_create, UpdateProfile, user_password_change

app_name = 'user_authentication'

urlpatterns = [
    path('registration/', user_create, name='signin'),
    path('login/', user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='log_out'),
    path('detail/', UpdateProfile.as_view(), name='profile'),
    path('change_password/', user_password_change, name='change_password'),
]

shop/templates/base_generic.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>

    <title>Shop</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/headers/">

    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getToken('csrftoken')

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }

            // Return null if not found
            return null;
        }

        var cart = JSON.parse(getCookie('cart'))

        if (cart == undefined) {
            cart = {}
            console.log('Cart Created!', cart)
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)

    </script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>

    {% block extra_js %}
        <script src="{% static 'js/shop.js' %}"></script>
    {% endblock %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">
</head>
<body>

<main>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top container-fluid p-3 text-bg-dark">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li>
                <a class="btn btn-dark" href="{% url 'store' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Store
                </a>
            </li>
            <li>
                <a class="btn btn-dark" href="{% url 'faq' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Faq
                </a>
            </li>
            <li>
                <a class="btn btn-dark" href="{% url 'about' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    About
                </a>
            </li>
            <li>
                <a class="btn btn-dark" href="{% url 'order_info' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    My orders
                </a>
            </li>
            <li>
                <button type="button" class="btn btn-dark contact-us" data-url="{% url 'contact_us_form' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Contact us
                </button>
            </li>
            <li>
                {% if user.is_staff %}
                    <a class="btn btn-dark" href="/admin/">
                        <span class="glyphicon glyphicon-plus"></span>
                        Admin panel
                    </a>
                {% endif %}
            </li>
        </ul>
        <div class="text-end">
            {% if user.is_authenticated %}
                <a class="btn btn-outline-light" href="{% url 'user_authentication:log_out' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Logout
                </a>
                <a class="btn btn-outline-warning" href="{% url 'user_authentication:profile' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Profile
                </a>
                <a class="btn btn-outline-light" href="{% url 'cart' %}">
                    <img id="cart" src="{% static 'images/cart.png' %}" width="25" height="20" fill="currentColor"
                         class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                </a>
            {% else %}
                <button type="button" class="btn btn-outline-light js-shop"
                        data-url="{% url 'user_authentication:login' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Login
                </button>
                <button type="button" class="btn btn-outline-warning js-shop"
                        data-url="{% url 'user_authentication:signin' %}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Sign in
                </button>
                <a class="btn btn-outline-light" href="{% url 'cart' %}">
                    <img id="cart" src="{% static 'images/cart.png' %}" width="25" height="20" fill="currentColor"
                         class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                </a>
            {% endif %}
        </div>
    </nav>

</main>
<div class="container" style="padding-top: 100px;">

    {% block content %}

    {% endblock %}
    {% block scripts %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <!-- You can alternatively load the minified version -->
        <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% include 'include/_modal.html' %}
</div>
</body>
</html>